spring.application.name=contact_book

jwt.public.key=${JWT_PUBLIC_KEY:file:/opt/keys/app.pub}
jwt.private.key=${JWT_PRIVATE_KEY:file:/opt/keys/app.key}


logging.level.org.springframework.security=DEBUG

server.error.include-stacktrace=never


spring.datasource.url=jdbc:postgresql://localhost:5432/contact_book
spring.datasource.username= postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.security.user.name=longobucco
spring.security.user.password=123

spring.mvc.hiddenmethodarguments=true
